### PR TITLE
Small dropdown style adjustements

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Fixes some issues highlighted by @gtsiolis. This is only first batch focusing on GitHub so far.
image

## Related Issue(s)

Fixes EXP-721

### CODE REVIEW

**Review by gtsiolis — APPROVED** [review]
Thanks, @filiptronicek. 🌮 

Code changes look good.

Do you know how can I test this in Firefox?

**Comment by filiptronicek** [comment]
@gtsiolis you can build it with 
```
pnpm plasmo build --target=firefox-mv2 && pnpm plasmo package --target=firefox-mv2
```

and then in `about:debugging#/runtime/this-firefox`, install it. Note that settings will not work in this mode, because Firefox disables storage for temporary extensions.

**Comment by gtsiolis** [comment]
Nice, UX LGTM. Thanks! 

Added https://linear.app/gitpod/issue/EXP-753/ to keep track of more improvements in the README.

**Comment by gtsiolis** [comment]
@filiptronicek I merged this but have no clue what happens with the automatic release etc. It would be nice if we could document this in the README also as described in EXP-753. 🏓

**Comment by filiptronicek** [comment]
Agree, @gtsiolis, the README deserves some more love, as there also is still a lot of outdated info. I'll look into it when I find the time, either this or next week.

**Pull request merged**
